# Generated by Django 5.2.3 on 2025-08-22 06:31

import books.models
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('slug', models.SlugField(blank=True, unique=True)),
                ('author', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True)),
                ('category', models.CharField(choices=[('Programming', 'Programming'), ('CSE', 'CSE'), ('ME', 'ME'), ('MI', 'MI'), ('CE', 'CE'), ('Math', 'Math'), ('Other', 'Other')], default='Other', max_length=50)),
                ('total_copies', models.PositiveIntegerField(default=1)),
                ('available_copies', models.PositiveIntegerField(default=1)),
                ('isbn', models.CharField(blank=True, help_text='Enter a unique ISBN (leave blank if not available)', max_length=13, null=True, unique=True)),
                ('cover_image', models.ImageField(blank=True, help_text='Upload JPG or PNG image', null=True, upload_to='book_covers/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['jpg', 'jpeg', 'png']), books.models.validate_image_size])),
                ('pdf_file', models.FileField(blank=True, help_text='Upload a PDF file', null=True, upload_to='book_pdfs/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['pdf']), books.models.validate_pdf_size])),
                ('available', models.BooleanField(default=True)),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
