# Generated by Django 5.2.3 on 2025-09-07 15:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_customuser_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studentregistration',
            name='course',
            field=models.CharField(choices=[('BTECH', 'B.Tech'), ('POLY', 'Polytechnic')], max_length=100),
        ),
        migrations.AlterField(
            model_name='studentregistration',
            name='year_of_study',
            field=models.IntegerField(choices=[(1, '1st Year'), (2, '2nd Year'), (3, '3rd Year'), (4, '4th Year')]),
        ),
    ]
